#!/bin/sh

# $Id$
#
# Copyright 1998 Sidney Cammeresi
# All rights reserved.
#
# You may use this file in accordance with the license of this distribution.
#
# Script to generate dynamically linked executables

gcc -nostdlib -nostartfiles $BLTSRCDIR/lib/crt0.o -L. -e _start -Wl,-dynamic-linker,/boot/lib/linker,-T,$BLTSRCDIR/util/blt_i386.x $@

